# Generated by Django 5.2.4 on 2025-07-04 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_ruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='es_conductor',
        ),
    ]
